### ISSUE TITLE
[SERVER] MySQL - NCP 구축

### ISSUE THREAD

**Issue by jangky000** [boostcamp-2020/IssueTracker-04#18]
### 요구사항
NCP 서버를 구축하고 MySQL을 설치 + ERD를 토대로 테이블 구축

#### Other

- [x] NCP 서버 설정
- [x]  ERD 설계
- [x]  CREATE SQL 작성
- [x] issueTracker 데이터베이스 구축
- [x] group4 사용자 생성
- [x] 테이블 생성

**Comment by Zigje9** [comment]
![image](https://user-images.githubusercontent.com/46099115/97280180-44da4300-187f-11eb-90d6-6994d501dba7.png)
